export type Category = { id: number; name: string; slug: string };
export type Article = { id:number; title:string; slug:string; excerpt:string; category:string; image:string; publishedAt:string; featured?:boolean; breaking?:boolean };
export const categories: Category[] = [
{id:1,name:"জগন্নাথ বিশ্ববিদ্যালয়",slug:"jagannath-university"},{id:2,name:"ক্যাম্পাস",slug:"campus"},{id:3,name:"শিক্ষা",slug:"education"},{id:4,name:"জাতীয়",slug:"national"},{id:5,name:"আন্তর্জাতিক",slug:"international"},{id:6,name:"প্রযুক্তি",slug:"technology"},{id:7,name:"ক্যারিয়ার",slug:"career"},{id:8,name:"খেলাধুলা",slug:"sports"},{id:9,name:"বিনোদন",slug:"entertainment"},{id:10,name:"মতামত",slug:"opinion"}];
export const articles: Article[] = [
{id:1,title:"জগন্নাথ বিশ্ববিদ্যালয়কে কেন্দ্র করে নতুন প্রজন্মের ডিজিটাল সংবাদযাত্রা",slug:"jnunews-digital-news-journey",excerpt:"ক্যাম্পাসের খবর, শিক্ষা, প্রযুক্তি ও তরুণদের গল্পকে দ্রুত এবং দায়িত্বশীলভাবে পাঠকের কাছে পৌঁছে দেওয়ার লক্ষ্য নিয়ে JnU News-এর যাত্রা।",category:"জগন্নাথ বিশ্ববিদ্যালয়",image:"https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1600&q=80",publishedAt:"১ সেপ্টেম্বর ২০২৬",featured:true,breaking:true},
{id:2,title:"ক্যাম্পাস সাংবাদিকতায় তথ্য যাচাই কেন আরও গুরুত্বপূর্ণ",slug:"fact-checking-in-campus-journalism",excerpt:"দ্রুততার পাশাপাশি নির্ভুলতা, উৎস যাচাই এবং প্রেক্ষাপট—বিশ্ববিদ্যালয় সাংবাদিকতার তিনটি গুরুত্বপূর্ণ ভিত্তি।",category:"ক্যাম্পাস",image:"https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80",publishedAt:"১ সেপ্টেম্বর ২০২৬"},
{id:3,title:"AI যুগে শিক্ষার্থীদের কোন দক্ষতাগুলো সবচেয়ে বেশি দরকার",slug:"future-skills-for-students-in-ai-era",excerpt:"AI literacy, critical thinking, communication এবং project-based learning এখন ভবিষ্যৎ কর্মক্ষেত্রের জন্য গুরুত্বপূর্ণ হয়ে উঠছে।",category:"প্রযুক্তি",image:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",publishedAt:"৩১ আগস্ট ২০২৬"},
{id:4,title:"উচ্চশিক্ষায় গবেষণা ও উদ্ভাবনের সুযোগ বাড়ছে",slug:"research-and-innovation-in-higher-education",excerpt:"বিশ্ববিদ্যালয় পর্যায়ে গবেষণাভিত্তিক শিক্ষা ও শিক্ষার্থী উদ্ভাবনকে গুরুত্ব দেওয়ার প্রবণতা বাড়ছে।",category:"শিক্ষা",image:"https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80",publishedAt:"৩১ আগস্ট ২০২৬"}];
