create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  copyright_text text default '© 2026 JnU News. All rights reserved.',
  facebook_url text,
  youtube_url text,
  instagram_url text,
  linkedin_url text,
  x_url text,
  updated_at timestamptz default now()
);

create table if not exists public.footer_links (
  id bigint generated by default as identity primary key,
  label text not null,
  url text not null,
  sort_order integer default 0,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ads (
  id bigint generated by default as identity primary key,
  title text,
  position text not null check (position in ('home_top','home_sidebar','home_middle','article_top','article_middle')),
  image_url text,
  link_url text,
  alt_text text,
  is_active boolean default true,
  start_at timestamptz,
  end_at timestamptz,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.site_settings enable row level security;
alter table public.footer_links enable row level security;
alter table public.ads enable row level security;

create policy "Public can read site settings" on public.site_settings for select using (true);
create policy "Public can read active footer links" on public.footer_links for select using (is_active = true);
create policy "Public can read active ads" on public.ads for select using (is_active = true and (start_at is null or start_at <= now()) and (end_at is null or end_at >= now()));

create policy "Authenticated users can manage site settings" on public.site_settings for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage footer links" on public.footer_links for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage ads" on public.ads for all to authenticated using (true) with check (true);

grant select on public.site_settings, public.footer_links, public.ads to anon;
grant select, insert, update, delete on public.site_settings, public.footer_links, public.ads to authenticated;
grant usage, select on sequence public.footer_links_id_seq, public.ads_id_seq to authenticated;

insert into public.site_settings (id, copyright_text)
values (1, '© 2026 JnU News. All rights reserved.')
on conflict (id) do nothing;

insert into public.footer_links (label,url,sort_order)
values
('আমাদের সম্পর্কে','/about',1),
('বিজ্ঞাপন','/advertise',2),
('সার্কুলেশন','/circulation',3),
('নীতি ও শর্ত','/terms',4),
('যোগাযোগ','/contact',5),
('নিউজলেটার','/newsletter',6)
on conflict do nothing;
