'use client';
import {FormEvent,useEffect,useState} from 'react';
import AdminFrame from '@/components/AdminFrame';
import {supabase} from '@/lib/supabase';

type LinkRow={id:number;label:string;url:string;sort_order:number;is_active:boolean};
type Settings={copyright_text:string;facebook_url:string;youtube_url:string;instagram_url:string;linkedin_url:string;x_url:string};
const emptySettings:Settings={copyright_text:'',facebook_url:'',youtube_url:'',instagram_url:'',linkedin_url:'',x_url:''};

export default function FooterAdmin(){
 const [settings,setSettings]=useState<Settings>(emptySettings);const [links,setLinks]=useState<LinkRow[]>([]);const [editing,setEditing]=useState<LinkRow|null>(null);const [label,setLabel]=useState('');const [url,setUrl]=useState('');const [sortOrder,setSortOrder]=useState(links.length+1);const [msg,setMsg]=useState('');
 async function load(){const [{data:s},{data:l}]=await Promise.all([supabase.from('site_settings').select('*').eq('id',1).maybeSingle(),supabase.from('footer_links').select('id,label,url,sort_order,is_active').order('sort_order')]);if(s)setSettings({copyright_text:s.copyright_text??'',facebook_url:s.facebook_url??'',youtube_url:s.youtube_url??'',instagram_url:s.instagram_url??'',linkedin_url:s.linkedin_url??'',x_url:s.x_url??''});setLinks((l??[]) as LinkRow[]);}
 useEffect(()=>{load();},[]);
 async function saveSettings(e:FormEvent){e.preventDefault();setMsg('');const {error}=await supabase.from('site_settings').upsert({id:1,...settings,updated_at:new Date().toISOString()});setMsg(error?error.message:'Footer settings save হয়েছে।');}
 async function saveLink(e:FormEvent){e.preventDefault();setMsg('');const payload={label,url,sort_order:Number(sortOrder)||0,is_active:editing?.is_active??true,updated_at:new Date().toISOString()};const {error}=editing?await supabase.from('footer_links').update(payload).eq('id',editing.id):await supabase.from('footer_links').insert(payload);if(error){setMsg(error.message);return;}setEditing(null);setLabel('');setUrl('');setSortOrder(links.length+1);setMsg('Footer link save হয়েছে।');load();}
 function edit(l:LinkRow){setEditing(l);setLabel(l.label);setUrl(l.url);setSortOrder(l.sort_order);}
 async function toggle(l:LinkRow){await supabase.from('footer_links').update({is_active:!l.is_active,updated_at:new Date().toISOString()}).eq('id',l.id);load();}
 async function remove(id:number){if(!confirm('এই footer link delete করবেন?'))return;await supabase.from('footer_links').delete().eq('id',id);load();}
 return <AdminFrame><div className="adminHeading"><div><p>Site Settings</p><h1>Footer</h1></div></div>{msg&&<div className="adminNote">{msg}</div>}<div className="twoColAdmin"><form className="adminPanel formStack" onSubmit={saveSettings}><h2>Copyright & Social Media</h2><label>Copyright Text<input value={settings.copyright_text} onChange={e=>setSettings({...settings,copyright_text:e.target.value})}/></label><label>Facebook URL<input value={settings.facebook_url} onChange={e=>setSettings({...settings,facebook_url:e.target.value})}/></label><label>YouTube URL<input value={settings.youtube_url} onChange={e=>setSettings({...settings,youtube_url:e.target.value})}/></label><label>Instagram URL<input value={settings.instagram_url} onChange={e=>setSettings({...settings,instagram_url:e.target.value})}/></label><label>LinkedIn URL<input value={settings.linkedin_url} onChange={e=>setSettings({...settings,linkedin_url:e.target.value})}/></label><label>X / Twitter URL<input value={settings.x_url} onChange={e=>setSettings({...settings,x_url:e.target.value})}/></label><button className="primaryBtn">Save Footer Settings</button></form><div><form className="adminPanel formStack" onSubmit={saveLink}><h2>{editing?'Footer Link Edit':'নতুন Footer Link'}</h2><label>Label<input required value={label} onChange={e=>setLabel(e.target.value)} placeholder="আমাদের সম্পর্কে"/></label><label>URL<input required value={url} onChange={e=>setUrl(e.target.value)} placeholder="/about অথবা https://..."/></label><label>Sort Order<input type="number" value={sortOrder} onChange={e=>setSortOrder(Number(e.target.value))}/></label><button className="primaryBtn">{editing?'Update Link':'Add Link'}</button>{editing&&<button type="button" className="smallBtn" onClick={()=>{setEditing(null);setLabel('');setUrl('')}}>Cancel</button>}</form><div className="adminPanel"><h2>Footer Links</h2><div className="adminTable">{links.map(l=><div className="adminRow adminRowWide" key={l.id}><div><strong>{l.label}</strong><span>{l.url} · #{l.sort_order} · {l.is_active?'Active':'Hidden'}</span></div><div className="adminActionGroup"><button className="smallBtn" onClick={()=>edit(l)}>Edit</button><button className="smallBtn" onClick={()=>toggle(l)}>{l.is_active?'Hide':'Show'}</button><button className="dangerBtn" onClick={()=>remove(l.id)}>Delete</button></div></div>)}</div></div></div></div></AdminFrame>;
}
