'use client';
import {FormEvent,useEffect,useState} from 'react';
import Image from 'next/image';
import AdminFrame from '@/components/AdminFrame';
import {supabase} from '@/lib/supabase';

type AdRow={id:number;title:string|null;position:string;image_url:string|null;link_url:string|null;alt_text:string|null;is_active:boolean;sort_order:number;start_at:string|null;end_at:string|null};
const positions=[['home_top','Homepage Top'],['home_sidebar','Homepage Sidebar'],['home_middle','Homepage Middle'],['article_top','Article Top'],['article_middle','Article Middle']];
export default function AdsAdmin(){
 const [items,setItems]=useState<AdRow[]>([]);const [editing,setEditing]=useState<AdRow|null>(null);const [title,setTitle]=useState('');const [position,setPosition]=useState('home_top');const [imageUrl,setImageUrl]=useState('');const [linkUrl,setLinkUrl]=useState('');const [altText,setAltText]=useState('');const [sortOrder,setSortOrder]=useState(0);const [startAt,setStartAt]=useState('');const [endAt,setEndAt]=useState('');const [msg,setMsg]=useState('');const [uploading,setUploading]=useState(false);
 async function load(){const {data}=await supabase.from('ads').select('*').order('position').order('sort_order');setItems((data??[]) as AdRow[]);}useEffect(()=>{load();},[]);
 function reset(){setEditing(null);setTitle('');setPosition('home_top');setImageUrl('');setLinkUrl('');setAltText('');setSortOrder(0);setStartAt('');setEndAt('');}
 function edit(a:AdRow){setEditing(a);setTitle(a.title??'');setPosition(a.position);setImageUrl(a.image_url??'');setLinkUrl(a.link_url??'');setAltText(a.alt_text??'');setSortOrder(a.sort_order??0);setStartAt(a.start_at?a.start_at.slice(0,16):'');setEndAt(a.end_at?a.end_at.slice(0,16):'');window.scrollTo({top:0,behavior:'smooth'});}
 async function upload(file:File){setUploading(true);setMsg('');const ext=file.name.split('.').pop()||'jpg';const path=`ads/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await supabase.storage.from('news-images').upload(path,file,{upsert:false});if(error){setMsg(error.message);setUploading(false);return;}const {data}=supabase.storage.from('news-images').getPublicUrl(path);setImageUrl(data.publicUrl);setUploading(false);}
 async function save(e:FormEvent){e.preventDefault();setMsg('');const payload={title:title||null,position,image_url:imageUrl||null,link_url:linkUrl||null,alt_text:altText||null,sort_order:Number(sortOrder)||0,start_at:startAt?new Date(startAt).toISOString():null,end_at:endAt?new Date(endAt).toISOString():null,is_active:editing?.is_active??true,updated_at:new Date().toISOString()};const {error}=editing?await supabase.from('ads').update(payload).eq('id',editing.id):await supabase.from('ads').insert(payload);if(error){setMsg(error.message);return;}setMsg('Advertisement save হয়েছে।');reset();load();}
 async function toggle(a:AdRow){await supabase.from('ads').update({is_active:!a.is_active,updated_at:new Date().toISOString()}).eq('id',a.id);load();}
 async function remove(id:number){if(!confirm('এই advertisement delete করবেন?'))return;await supabase.from('ads').delete().eq('id',id);load();}
 return <AdminFrame><div className="adminHeading"><div><p>Monetization</p><h1>Advertisements</h1></div></div>{msg&&<div className="adminNote">{msg}</div>}<div className="twoColAdmin"><form className="adminPanel formStack" onSubmit={save}><h2>{editing?'Advertisement Edit':'নতুন Advertisement'}</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Position<select value={position} onChange={e=>setPosition(e.target.value)}>{positions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Ad Image<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label>{uploading&&<small>Uploading...</small>}{imageUrl&&<Image className="adminPreview" src={imageUrl} alt="Ad preview" width={700} height={220}/>}<label>Image URL<input value={imageUrl} onChange={e=>setImageUrl(e.target.value)}/></label><label>Destination URL<input value={linkUrl} onChange={e=>setLinkUrl(e.target.value)} placeholder="https://..."/></label><label>Alt Text<input value={altText} onChange={e=>setAltText(e.target.value)}/></label><label>Sort Order<input type="number" value={sortOrder} onChange={e=>setSortOrder(Number(e.target.value))}/></label><label>Start Date/Time<input type="datetime-local" value={startAt} onChange={e=>setStartAt(e.target.value)}/></label><label>End Date/Time<input type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)}/></label><button className="primaryBtn">{editing?'Update Ad':'Add Ad'}</button>{editing&&<button type="button" className="smallBtn" onClick={reset}>Cancel</button>}</form><div className="adminPanel"><h2>সব Advertisement</h2><div className="adminTable">{items.map(a=><div className="adminRow adminRowWide" key={a.id}><div><strong>{a.title||positions.find(p=>p[0]===a.position)?.[1]||a.position}</strong><span>{a.position} · {a.is_active?'Active':'Hidden'} · #{a.sort_order}</span></div><div className="adminActionGroup"><button className="smallBtn" onClick={()=>edit(a)}>Edit</button><button className="smallBtn" onClick={()=>toggle(a)}>{a.is_active?'Hide':'Show'}</button><button className="dangerBtn" onClick={()=>remove(a.id)}>Delete</button></div></div>)}{!items.length&&<p className="emptyState">এখনও কোনো advertisement নেই।</p>}</div></div></div></AdminFrame>;
}
